// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrMNZg7Pq2YbSzPc5Y0QDFzw71VcDVN6I',
    appId: '1:1013770255464:web:97c5f1cdca885bae664fdd',
    messagingSenderId: '1013770255464',
    projectId: 'seeroms',
    authDomain: 'seeroms.firebaseapp.com',
    storageBucket: 'seeroms.appspot.com',
    measurementId: 'G-5SY92BKCRY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0BgdJw6yvHFHO9pIFm5mdMNg88uotpig',
    appId: '1:1013770255464:android:996296aa35165400664fdd',
    messagingSenderId: '1013770255464',
    projectId: 'seeroms',
    storageBucket: 'seeroms.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmMoaYbpg_jdPAE1QDq4rndx7UW2vZs54',
    appId: '1:1013770255464:ios:eb8cd67c95d416ba664fdd',
    messagingSenderId: '1013770255464',
    projectId: 'seeroms',
    storageBucket: 'seeroms.appspot.com',
    iosClientId: '1013770255464-fbtkird93t5950rgcf96ffvrj5miujcm.apps.googleusercontent.com',
    iosBundleId: 'com.example.seerooms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmMoaYbpg_jdPAE1QDq4rndx7UW2vZs54',
    appId: '1:1013770255464:ios:eb8cd67c95d416ba664fdd',
    messagingSenderId: '1013770255464',
    projectId: 'seeroms',
    storageBucket: 'seeroms.appspot.com',
    iosClientId: '1013770255464-fbtkird93t5950rgcf96ffvrj5miujcm.apps.googleusercontent.com',
    iosBundleId: 'com.example.seerooms',
  );
}
